# Facebook account credentials
account:
  email: FACEBOOK_EMAIL
  password: FACEBOOK_PASSWORD

# Threads to listen to
threads:
  - 162123511236172
  - 192123512310277:  # thread id
    aliases:
      - 4:            # facebook id of person
        - zuck
        - mark
        - zuckerberg
      - 5:
        - chris
        - hughes

app:
  stateFile: /data/facebook-group-chat-bot/appstate.json  # where to save the state of the Facebook chat API
  commandEscape: "#"        # character all commands to the bot should be preceeded with (e.g. #ping)

modules:
  whodis:
    recentMessagesCount: 50   # how many recent messages to search for photos
    googlApiKey: YOUR_GOOGL_API_KEY   # https://developers.google.com/url-shortener/v1/getting_started?csw=1#APIKey

  showme:
    defaultImageCount: 1     # how many images to return
    maxImageCount: 10        # max number of images to return
    cseId: CSE_ID            # info how to obtain these:
    cseApiKey: CSE_API_KEY   # https://github.com/vdemedes/google-images

  heIsRisen:                 # replies "<name> is risen!" when a person on the watch list texts for the first time in the last 'timeLimit' minutes or 'msgLimit' messages
    timeLimit: 720           # how long the user must have been inactive (in minutes)
    msgLimit: 200            # how many messages to look back on for the user
    watchEveryone: false     # whether to watch everyone in the chat
    watchList:               # list of ids of people to watch; ignored if watchEveryone is true
      - USER_ID_1
      - USER_ID_2