# Facebook account credentials
account:
  email: FACEBOOK_EMAIL
  password: FACEBOOK_PASSWORD

# Threads to listen to
threads:
  - 162123511236172
  - 192123512310277

app:
  stateFile: appstate.json  # where to save the state of the Facebook chat API
  commandEscape: "#"        # character all commands to the bot should be preceeded with (e.g. #ping)

modules:
  whodis:
    recentMessagesCount: 50   # how many recent messages to search for photos
    googlApiKey: YOUR_GOOGL_API_KEY   # https://developers.google.com/url-shortener/v1/getting_started?csw=1#APIKey
  showme:
    defaultImageCount: 1     # how many images to return
    maxImageCount: 10        # max number of images to return
    cseId: CSE_ID            # info how to obtain these:
    cseApiKey: CSE_API_KEY   # https://github.com/vdemedes/google-images